# flux_demo/clusters/dev/vault-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-deployment-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/stg/apps/vault/"  # Ensure this matches the path in gitops_k8s_tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: vault-deployment
    namespace: flux-system
  targetNamespace: vault
