apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-app-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/stg/apps/vault"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-tools
    namespace: flux-system
  targetNamespace: vault
